blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/SafeExamBrowser/seb-win-refactoring/discussions
    about: Discuss topics or ask and answer questions related to Safe Exam Browser.
